language: node_js
node_js:
    - 12

cache:
    directories:
        - 'node_modules'


install:
    - npm install newman

before_script:
    - node --version
    - npm --version
    - node_modules/.bin/newman --version
        
script:
    - npm run lint
    - npm run build
    - npm run test
    - npm run dev &

    - node_modules/.bin/newman run tests/testcollection.json
