language: node_js
node_js:
    - 12

cache:
    directories:
        - 'node_modules'

install:
    - npm install newma

before_script:
    - node --version
    - npm --version
    - node_modules/.bin/newman --version

script:
    - npm install
    - npm run lint
    - npm run build
    - npm run test
